# build and test
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  # we call `pnpm playwright install` instead
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

jobs:
  # "checks" job runs on linux + 16 only and checks that install, build, lint and audit work
  # it also primes the pnpm store cache for linux, important for downstream tests
  checks:
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # pseudo-matrix for convenience, NEVER use more than a single combination
        node: [16]
        os: [ubuntu-latest]
    outputs:
      build_successful: ${{ steps.build.outcome == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: install pnpm
        shell: bash
        run: |
          PNPM_VER=$(jq -r '.packageManager | if .[0:5] == "pnpm@" then .[5:] else "packageManager in package.json does not start with pnpm@\n" | halt_error(1)  end' package.json)
          echo installing pnpm version $PNPM_VER
          npm i -g pnpm@$PNPM_VER
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: install
        run: pnpm install --frozen-lockfile --prefer-offline
# reactivate this when there is a build step
#      - name: build
#        id: build
#        run: pnpm run build
      - name: lint
        if: (${{ success() }} || ${{ failure() }})
        run: pnpm run lint
      - name: audit
        if: (${{ success() }} || ${{ failure() }})
        run: pnpm audit

  # this is the test matrix
  # it is skipped if the build step of the checks job wasn't successful (still runs if lint or audit fail)
  test:
    needs: checks
    if: (${{ success() }} || ${{ failure() }}) && (${{ needs.checks.output.build_successful }})
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [16]
        os: [ubuntu-latest, macos-latest, windows-latest]
        svelte: [4]
        include:
          - node: 14
            os: ubuntu-latest
            svelte: 3
          - node: 18
            os: ubuntu-latest
            svelte: 4
          - node: 20
            os: ubuntu-latest
            svelte: 4
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: install pnpm
        if: matrix.node != 14
        shell: bash
        run: |
          PNPM_VER=$(jq -r '.packageManager | if .[0:5] == "pnpm@" then .[5:] else "packageManager in package.json does not start with pnpm@\n" | halt_error(1)  end' package.json)
          echo installing pnpm version $PNPM_VER
          npm i -g pnpm@$PNPM_VER
      - name: install legacy pnpm for node14
        if: matrix.node == 14
        run: |
          npm i -g pnpm@^7.33.0
          tmppkg="$(jq '.engines.pnpm = "^7.33.0"' package.json)" && echo -E "${tmppkg}" > package.json && tmppkg=""
      - name: use svelte 3
        if: matrix.svelte == 3
        run: |
          tmppkg="$(jq '.devDependencies.svelte = "^3.59.2"' package.json)" && echo -E "${tmppkg}" > package.json && tmppkg=""
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: install
        if: matrix.node != 14 && matrix.svelte != 3
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: install for node14 or svelte3
        if: matrix.node == 14 || matrix.svelte == 3
        run: pnpm install --no-frozen-lockfile --prefer-offline 
      - name: install playwright chromium
        run: cd playground && pnpm playwright install chromium
      - name: run tests
        run: pnpm test
